<?php

ini_set('display_startup_errors',1);
ini_set('display_errors',1);
error_reporting(-1);

session_start();
if (!isset($_SESSION['username'])) {
        header("Location: login");
}

$username = $_SESSION['username'];

date_default_timezone_set('UTC');

$issueDate = formatTime(time());

$db = new SQLite3('db/ptr.db');


$ptrId =  trim(file_get_contents("ptr-id.log"));
$ptrFileId = trim(file_get_contents("ptr-file-id.log"));
$generatorId = trim(file_get_contents("generator-id.log"));

$configs = $_GET['configs'];

$configs = explode(',', $configs);
$number_configs = count($configs);

//Convert formatted date to UNIX time, and add 54000s for 15:00
$start = strtotime($_GET['start']) + 54000;

//find end time by adding two days
$end = $start + (2*24*60*60);
//leave 1 minute at end of slot for shutdown etc.
//$end = $end - 60;

$duration = $end - $start;

function formatTime($itime) {
	//Slightly cheating, atom time includes milliseconds of fixed length
	return substr(date(DATE_ATOM, $itime), 0, -6);
}

function formatDuration($seconds) {
	if ($seconds < (60*60*24)) {
		$dur =  "00T".gmdate("H:i:s", $seconds);
	}
	else {
		$seconds = $seconds - (60*60*24);
		$dur =  "01T".gmdate("H:i:s", $seconds);
	}
	return $dur;
}

function generatePtr($startTime, $endTime, $config) {
	global $db, $username, $issueDate, $ptrId, $ptrFileId, $generatorId;
	
	$startTime = $startTime + (10*60);

	$transferPST = formatTime($startTime);
	$transferEST = formatTime($startTime);
	$transferLST = formatTime($startTime + (60*5));
	
	$dataPST = formatTime($startTime + 130);
	$dataEST = formatTime($startTime + 130);
	$dataLST = formatTime($startTime + (7*60) + 10);
	
	$dataDuration = $endTime - $startTime;
	//leave 5 minutes at the end of each capture for padding
	$dataDuration = $dataDuration - ((10*60) + 10);
	$transferDuration = formatDuration(120);
	$dataDuration = formatDuration($dataDuration-120);

	$ptrText = <<<EOT
	<ptr>
        	<domain>TDS-1</domain>
        	<ptrId>{$ptrId}</ptrId>
        	<preferredStartTime>{$transferPST}</preferredStartTime>
        	<earliestStartTime>{$transferEST}</earliestStartTime>
        	<latestStartTime>{$transferLST}</latestStartTime>
        	<duration>{$transferDuration}</duration>
        	<taskPriority>0</taskPriority>
        	<explanatoryText>0</explanatoryText>
        	<TASK_LUCID_TRANSFER>
        	    <FileName>{$config}</FileName>
        	</TASK_LUCID_TRANSFER>
    	</ptr>
EOT;
	//Store transfer PTR in database
	$db->exec("INSERT INTO log VALUES(\"{$generatorId}\", \"{$ptrFileId}\", \"{$ptrId}\", \"transfer\", \"{$transferEST}\", \"{$transferLST}\", \"{$transferPST}\", \"{$transferDuration}\", \"{$config}\", \"false\", \"{$username}\", \"{$issueDate}\");");

	$ptrId++;

	$ptrText .= <<<EOT

    	<ptr>
        	<domain>TDS-1</domain>
        	<ptrId>{$ptrId}</ptrId>
        	<preferredStartTime>{$dataPST}</preferredStartTime>
        	<earliestStartTime>{$dataEST}</earliestStartTime>
        	<latestStartTime>{$dataLST}</latestStartTime>
        	<duration>{$dataDuration}</duration>
        	<taskPriority>0</taskPriority>
        	<explanatoryText>0</explanatoryText>
        	<TASK_LUCID_DATA/>
	</ptr>

EOT;

	//...and data
	$db->exec("INSERT INTO log VALUES(\"{$generatorId}\", \"{$ptrFileId}\", \"{$ptrId}\", \"data\", \"{$dataEST}\", \"{$dataLST}\", \"{$dataPST}\", \"{$dataDuration}\", \"{$config}\", \"false\", \"{$username}\", \"{$issueDate}\");");

	$ptrId++;
	return $ptrText;

}


//print "Start time is ".$start; print "<br>"; 
//print "End time is ".$end; print "<br><br>";

//print "There are ".$number_configs." config files <br><br>";

//round down so the capture never overruns the slot
$time_for_config = round($duration/$number_configs, 0, PHP_ROUND_HALF_DOWN); 
$ctime = 0;

//initialise variable to store PTRs
$PTRs = array();

//work out start/end time for each capture and call generatePtr()
foreach($configs as $config) {
	$startTime = $start + $ctime;
	//print $config." starts at ".$startTime;
	$ctime += $time_for_config;
	//print " ";
	$endTime = $start + $ctime - 1;
	//print $config." ends at ".$endTime;
	//print "<br>";
	array_push($PTRs, generatePtr($startTime, $endTime, $config));
}


$ptrFile = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
<ptrFile xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"PtrFile.xsd\">
    <fileHeader>
        <source>LUCID-PI</source>
        <destination>MPS</destination>
        <issueDate>{$issueDate}</issueDate>
        <information>Generated by LUCID PTR Generator</information>
    </fileHeader>
    <ptrFileId>{$ptrFileId}</ptrFileId>

";

foreach($PTRs as $PTR) {
	$ptrFile .= $PTR;
}

$ptrFile .= "</ptrFile>"; 
?>

<!DOCTYPE html>
<title>PTR Generator - Generated Code</title>
<link rel = "stylesheet" href = "prism/prism.css">
<script src = "prism/prism.js"></script>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

<style>
#details, #links {
font-family: Open Sans;
font-weight: 300;
font-size: 17px;
}
input, textarea {
width: 765px;
padding-right: 15px;
height: 50px;
padding-left: 15px;
background-color: #dddddd;
border: none;
margin-top: 5px;
}
input[type="button"] {
width: 100px;
align: right;
margin-left: 690px;
margin-top: 20px;
background-color: #259b24;
color: white;
}
select {
width: 100px;
height: 40px;
border: none;
background-color: #dddddd;
}
.small {
width: 50px;
}
#header {
width: 100%;
height: 90px;
background-color: #dddddd;
position: absolute;
top: 0;
left: 0;
text-align: center;
font-size: 60px;
font-family: Open Sans;
font-weight: 300;
padding-top: 30px;
color: #333333;
border-top: 3px solid #333333;
}
body {
padding-top: 130px;
}
#details {
position: absolute;
top: 90px;
right: 10px;
font-weight: 300;
}
#container {
    width: 800px;
    margin: 20px auto;
}
select {
margin-top: 5px;
}
#links div {
width: 150px;
height: 40px;
background-color: #259b24;
line-height: 40px;
text-align: center;
float: left;
margin-left: 10px;
}
#links a {
text-decoration: none;
color: white;
}
#details a {
color: #333333;
text-decoration: none;
}
</style>

<div id = "header">
<img src="lucid.jpg" width="60" style="border-radius: 3px; position: relative; top: 6px;">
PTR GENERATOR
</div>
<div id = "details">
<?php print $_SESSION['username']; ?> (<a href = "login/?action=logout">log out</a>)
</div>
<br>
<div id = "links">
<div><a href = "upload.php?id=<?php print $generatorId; ?>">Upload to SSTL</a></div>
<div style = "background-color: #5677fc"><a href = "download.php?id=<?php print $generatorId; ?>">Download File</a></div>
</div>
<br><br>
<pre style = "background:white; font-size: 13px;"><code class = "language-markup" style = "background: white">

<?php print htmlentities($ptrFile); ?>

</code></pre>

<?php
//print $generatorId;
file_put_contents("generated/".$generatorId.".ptr", $ptrFile);
file_put_contents("generated/".$generatorId.".ptrmeta", $ptrId);
$generatorId++;
file_put_contents("generator-id.log", $generatorId);
?>

